export * from './Billet';
export * from './CopyAndPastePix';
export * from './DemandPix';
export * from './Extract';
export * from './ExtractPerId';
export * from './KeysPix';
export * from './Login';
export * from './DashboardPage';
export * from './Payments';
export * from './Pix';
export * from './Profile';
export * from './Forgot'
export * from './Signup';
export * from './Transfer';
export * from './TransferPix';
export * from './VerifyAccount';
export * from './VerifyStatus';
export * from './Process';
export * from './Comprovant'